//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class a {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal a() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.a", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    모두에 대해 현재 스레드의 CurrentUICulture 속성을 재정의합니다
        ///   현재 스레드의 CurrentUICulture 속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   존재하지 않는 아이디입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a11 {
            get {
                return ResourceManager.GetString("a11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   고객사코드가 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a12 {
            get {
                return ResourceManager.GetString("a12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호가 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a13 {
            get {
                return ResourceManager.GetString("a13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연계코드가 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a14 {
            get {
                return ResourceManager.GetString("a14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML 데이터가 올바르지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a21 {
            get {
                return ResourceManager.GetString("a21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부가정보 데이터가 올바르지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a22 {
            get {
                return ResourceManager.GetString("a22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 계산서가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a23 {
            get {
                return ResourceManager.GetString("a23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타 사업자 계산서 자료를 등록할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a28 {
            get {
                return ResourceManager.GetString("a28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위수탁 발행시 위수탁 사업자번호는 필수항목입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a29 {
            get {
                return ResourceManager.GetString("a29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위수탁 발행시 위수탁 사업자번호가 공급자 또는 공급받는자 사업자번호와 동일할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a30 {
            get {
                return ResourceManager.GetString("a30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일반 발행시 위수탁 사업자번호가 존재하면 안됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a31 {
            get {
                return ResourceManager.GetString("a31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지원하지 않은 상태로 변경하려 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a32 {
            get {
                return ResourceManager.GetString("a32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태를 변경할 수 있는 권한이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a33 {
            get {
                return ResourceManager.GetString("a33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청 상태가 적절하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a34 {
            get {
                return ResourceManager.GetString("a34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요청한 승인번호의 개수와 이메일주소의 개수가 일치하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a35 {
            get {
                return ResourceManager.GetString("a35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 공인인증서가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a42 {
            get {
                return ResourceManager.GetString("a42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 공인인증서의 유효기간이 만료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a43 {
            get {
                return ResourceManager.GetString("a43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연계코드에 값이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a50 {
            get {
                return ResourceManager.GetString("a50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원가입/수정 권한이 없는 연계사입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a51 {
            get {
                return ResourceManager.GetString("a51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   값이 존재하지 않는 파라미터가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a52 {
            get {
                return ResourceManager.GetString("a52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 가입된 회원입니다. ID : 회원ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a53 {
            get {
                return ResourceManager.GetString("a53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록된 회원정보가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a54 {
            get {
                return ResourceManager.GetString("a54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호가 맞지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a55 {
            get {
                return ResourceManager.GetString("a55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   날짜의 형식은 YYYYMMDD 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a56 {
            get {
                return ResourceManager.GetString("a56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최대 검색기간을 초과하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a57 {
            get {
                return ResourceManager.GetString("a57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포인트가 부족합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a58 {
            get {
                return ResourceManager.GetString("a58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   포인트 정보가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a59 {
            get {
                return ResourceManager.GetString("a59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전자서명시 에러가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a60 {
            get {
                return ResourceManager.GetString("a60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회된 데이터가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a90 {
            get {
                return ResourceManager.GetString("a90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리 중 오류가 발생했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a91 {
            get {
                return ResourceManager.GetString("a91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알 수 없는 오류가 발생했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a99 {
            get {
                return ResourceManager.GetString("a99", resourceCulture);
            }
        }
    }
}
