//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class b {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal b() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.b", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    모두에 대해 현재 스레드의 CurrentUICulture 속성을 재정의합니다
        ///   현재 스레드의 CurrentUICulture 속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   작성일자가 발행일시 이후일 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8010 {
            get {
                return ResourceManager.GetString("b8010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   승인번호의 일자는 작성일자와 같아야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8020 {
            get {
                return ResourceManager.GetString("b8020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   승인번호의 국세청 등록번호를 확인 하시기 바랍니다. (41000040)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8021 {
            get {
                return ResourceManager.GetString("b8021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   승인번호는 숫자와 영문 소문자로만 구성되어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8022 {
            get {
                return ResourceManager.GetString("b8022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세금계산서 종류는 01,02,03,04 중 하나여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8030 {
            get {
                return ResourceManager.GetString("b8030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세금계산서 분류는 01,02,03,05 중 하나여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8031 {
            get {
                return ResourceManager.GetString("b8031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급자와 공급받는자의 사업자번호가 같을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8040 {
            get {
                return ResourceManager.GetString("b8040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급자 사업자 번호를 검증합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8041 {
            get {
                return ResourceManager.GetString("b8041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급자 상호는 필수입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8042 {
            get {
                return ResourceManager.GetString("b8042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급자 대표자명은 필수입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8043 {
            get {
                return ResourceManager.GetString("b8043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급받는자가 사업자일 경우 사업자번호를 검증합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8050 {
            get {
                return ResourceManager.GetString("b8050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급받는자가 개인일 경우 주민번호를 검증합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8051 {
            get {
                return ResourceManager.GetString("b8051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급받는자의 사업자번호 문자수가 올바르지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8052 {
            get {
                return ResourceManager.GetString("b8052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급받는자의 상호는 필수입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8053 {
            get {
                return ResourceManager.GetString("b8053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급받는자의 대표자명은 필수입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8054 {
            get {
                return ResourceManager.GetString("b8054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위수탁인 경우 수탁자 사업자번호를 검증합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8060 {
            get {
                return ResourceManager.GetString("b8060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위수탁인 경우 수탁자 상호는 필수입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8061 {
            get {
                return ResourceManager.GetString("b8061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위수탁인 경우 수탁자 대표자명은 필수입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8062 {
            get {
                return ResourceManager.GetString("b8062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위수탁이 아닌 경우 수탁자 사업자번호가 있어선 안됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8063 {
            get {
                return ResourceManager.GetString("b8063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위수탁이 아닌 경우 수탁자 상호가 있어선 안됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8064 {
            get {
                return ResourceManager.GetString("b8064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위수탁이 아닌 경우 수탁자 대표자명이 있어선 안됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8065 {
            get {
                return ResourceManager.GetString("b8065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영수/청구 구분코드는 01,02중 하나여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8070 {
            get {
                return ResourceManager.GetString("b8070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급가는 0일 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8080 {
            get {
                return ResourceManager.GetString("b8080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영세율이 아닐 경우 세액이 0일 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8081 {
            get {
                return ResourceManager.GetString("b8081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정계산서가 아닌 경우 공급가액이 음수가 될 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8082 {
            get {
                return ResourceManager.GetString("b8082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정계산서가 아닌 경우 세액이 0일 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8083 {
            get {
                return ResourceManager.GetString("b8083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정계산서가 아닌 경우 수정사유에 값이 없어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8084 {
            get {
                return ResourceManager.GetString("b8084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정계산서일 경우 수정코드가 반드시 있어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8090 {
            get {
                return ResourceManager.GetString("b8090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정계산서의 수정코드는 01,02,03,04,05,06중 하나여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8091 {
            get {
                return ResourceManager.GetString("b8091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품목의 일자는 YYYYMMDD 형식이어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8100 {
            get {
                return ResourceManager.GetString("b8100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품목 등록시에도 공급가액이 0일 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8101 {
            get {
                return ResourceManager.GetString("b8101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계산서 공급가액과 품목의 공급가액의 합계가 일치해야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8102 {
            get {
                return ResourceManager.GetString("b8102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계산서의 작성일자와 품목의 일자 중 하나 이상은 일치해야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8103 {
            get {
                return ResourceManager.GetString("b8103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계산서의 작성일자보다 품목의 일자가 미래 날짜일수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8104 {
            get {
                return ResourceManager.GetString("b8104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계산서의 작성년월과 품목의 년월은 일치해야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8105 {
            get {
                return ResourceManager.GetString("b8105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계산서의 합계금액과 현금,수표,어음,외상미수금의 합은 일치해야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8106 {
            get {
                return ResourceManager.GetString("b8106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품목의 거래일자 중 하나는 작성일과 같아야합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string b8107 {
            get {
                return ResourceManager.GetString("b8107", resourceCulture);
            }
        }
    }
}
