//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class d {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal d() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.d", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    모두에 대해 현재 스레드의 CurrentUICulture 속성을 재정의합니다
        ///   현재 스레드의 CurrentUICulture 속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   공급사업자사업자번호 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR001 {
            get {
                return ResourceManager.GetString("ERR001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급받는(사업)자사업자번호 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR002 {
            get {
                return ResourceManager.GetString("ERR002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수탁사업자등록번호 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR003 {
            get {
                return ResourceManager.GetString("ERR003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전송일시 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR004 {
            get {
                return ResourceManager.GetString("ERR004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발행일시가 유효하지 않은 경우, 발행일시가 전송일시 이후인 경우과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR005 {
            get {
                return ResourceManager.GetString("ERR005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작성일자가 유효하지 않은 경우, 작성일자가 발행일시 이후인 경우, 해당 과세 기산 내의 자료가 아닌 경우(수정세금계산서의 경우는 제외)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR006 {
            get {
                return ResourceManager.GetString("ERR006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공급가액과 세액의 부호가 다른 경우, 수정세금계산서의 환입 또는 계약의 해제 시 금액이 + 값인 경우과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR007 {
            get {
                return ResourceManager.GetString("ERR007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   코드 유형 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR008 {
            get {
                return ResourceManager.GetString("ERR008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폐업 사업자 발행 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR009 {
            get {
                return ResourceManager.GetString("ERR009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   국세청 등록번호 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR010 {
            get {
                return ResourceManager.GetString("ERR010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   당초승인번호 오류. (수정세금계산서 발행 시 당초승인번호를 잘못 기입했을 경우 발생)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR011 {
            get {
                return ResourceManager.GetString("ERR011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기타 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR099 {
            get {
                return ResourceManager.GetString("ERR099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SUC001 {
            get {
                return ResourceManager.GetString("SUC001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전자서명이 유효하지 않은 경우과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SUC002 {
            get {
                return ResourceManager.GetString("SUC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   승인번호 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SUC003 {
            get {
                return ResourceManager.GetString("SUC003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전자세금계산서 스키마 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SUC004 {
            get {
                return ResourceManager.GetString("SUC004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 전송된 승인번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SYS002 {
            get {
                return ResourceManager.GetString("SYS002", resourceCulture);
            }
        }
    }
}
