//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class taxWebErr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal taxWebErr() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.taxWebErr", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    모두에 대해 현재 스레드의 CurrentUICulture 속성을 재정의합니다
        ///   현재 스레드의 CurrentUICulture 속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   시스템에서 에러를 알려줍니다.{이건 메시지 아닙}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a1001 {
            get {
                return ResourceManager.GetString("a1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세금계산서 발급 성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a200 {
            get {
                return ResourceManager.GetString("a200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나이스 회원가입이 되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a201 {
            get {
                return ResourceManager.GetString("a201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세금계산서 인증서가 등록 되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a202 {
            get {
                return ResourceManager.GetString("a202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 발급 시도로그 저장 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a203 {
            get {
                return ResourceManager.GetString("a203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 발급 성공로그 저장 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a204 {
            get {
                return ResourceManager.GetString("a204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   세금계산서 발급실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a205 {
            get {
                return ResourceManager.GetString("a205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인증서 유효기간이 지났습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a206 {
            get {
                return ResourceManager.GetString("a206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a500 {
            get {
                return ResourceManager.GetString("a500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   찾을 수 없는 핸드폰 번호입니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a501 {
            get {
                return ResourceManager.GetString("a501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패스워드(생년월일)가 일치하지 않습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a502 {
            get {
                return ResourceManager.GetString("a502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원님은 사용할 수 없는 상태입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a505 {
            get {
                return ResourceManager.GetString("a505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원님은 가입승인을 받으시기 바랍니다.(관리자에게 문의바랍니다.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a506 {
            get {
                return ResourceManager.GetString("a506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파라메터에러과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string a517 {
            get {
                return ResourceManager.GetString("a517", resourceCulture);
            }
        }
    }
}
